// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBUVsKMh1ozbv62nZSUOUQxNxbQgIDi7k',
    appId: '1:325414220853:android:d7b1f9ed0e60394a5dad7c',
    messagingSenderId: '325414220853',
    projectId: 'eduspace-app',
    storageBucket: 'eduspace-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Rdkr6EkYaFC2SwVmRiEwkrhvVDe0rqA',
    appId: '1:325414220853:ios:559b0c5f4d586a465dad7c',
    messagingSenderId: '325414220853',
    projectId: 'eduspace-app',
    storageBucket: 'eduspace-app.firebasestorage.app',
    iosBundleId: 'com.example.learningManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Rdkr6EkYaFC2SwVmRiEwkrhvVDe0rqA',
    appId: '1:325414220853:ios:559b0c5f4d586a465dad7c',
    messagingSenderId: '325414220853',
    projectId: 'eduspace-app',
    storageBucket: 'eduspace-app.firebasestorage.app',
    iosBundleId: 'com.example.learningManagementApp',
  );
}
